# theme.toml template for a Hugo theme
# See https://github.com/gohugoio/hugoThemes#themetoml for an example

name = "Iriss Course"
license = "MIT"
licenselink = "https://github.com/irissorg/iriss-course/blob/main/LICENSE"
description = ""
tags = ['responsive']
features = []
min_version = "1.00"

[author]
  name = "HTML5 and Up, Ian Phillip, Lesley Duff, Paul Hart"
  homepage = ""

# If porting an existing theme
[original]
  name = ""
  homepage = ""
  repo = ""
